version: '3'

services:
  postgres:
    container_name: onlyours-postgres
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ./:/app/
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_HOST=onlyours-postgres
      - POSTGRES_PORT=5432
      - JWT_SCRET_KEY=jiof73mbofdm
