// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/shinYeongHyeon/onlyOurs-api/ent/schema"
	"github.com/shinYeongHyeon/onlyOurs-api/ent/users"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	usersFields := schema.Users{}.Fields()
	_ = usersFields
	// usersDescName is the schema descriptor for name field.
	usersDescName := usersFields[0].Descriptor()
	// users.DefaultName holds the default value on creation for the name field.
	users.DefaultName = usersDescName.Default.(string)
}
